# Generated by Django 2.2.12 on 2020-09-08 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cancha',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=40, verbose_name='Descripcion')),
                ('direccion', models.CharField(max_length=40, verbose_name='Direccion')),
                ('valor', models.CharField(max_length=40, verbose_name='Valor hora')),
            ],
            options={
                'verbose_name': 'Cancha',
                'verbose_name_plural': 'Canchas',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(max_length=40, verbose_name='Nombre region')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regiones',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Superficie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Superficie',
                'verbose_name_plural': 'Superficies',
            },
        ),
        migrations.CreateModel(
            name='Tipo_cancha',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo de cancha',
                'verbose_name_plural': 'Tipos de canchas',
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lat', models.CharField(max_length=100, verbose_name='Latitud')),
                ('lng', models.CharField(max_length=100, verbose_name='Longitud')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contrasenia', models.CharField(max_length=40, verbose_name='Contraseña')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.Roles')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hora_inicio', models.TimeField(verbose_name='Desde')),
                ('hora_fin', models.TimeField(verbose_name='Hasta')),
                ('fecha_reserva', models.DateField(verbose_name='Fecha de reserva')),
                ('Cancha_r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.cancha')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.Usuario')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=40, verbose_name='Nombres')),
                ('apellidop', models.CharField(max_length=40, verbose_name='Apellido paterno')),
                ('apellidom', models.CharField(max_length=40, verbose_name='Apellido materno')),
                ('direccion', models.CharField(max_length=60, verbose_name='Direccion')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.Ciudad')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hora_inicio', models.TimeField(verbose_name='hora inicio')),
                ('hora_termino', models.TimeField(verbose_name='hora termino')),
                ('dia', models.CharField(max_length=15, verbose_name='Dia de semana')),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.cancha')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_comuna', models.CharField(max_length=40, verbose_name='Nombre comuna')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.Region')),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
            },
        ),
        migrations.AddField(
            model_name='ciudad',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.Comuna'),
        ),
        migrations.CreateModel(
            name='CentroDeportivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=40, verbose_name='Nombre')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.Ubicacion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cancha',
            name='centro_dep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.CentroDeportivo'),
        ),
        migrations.AddField(
            model_name='cancha',
            name='servicios',
            field=models.ManyToManyField(to='Base.Servicio'),
        ),
        migrations.AddField(
            model_name='cancha',
            name='superfice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.Superficie'),
        ),
        migrations.AddField(
            model_name='cancha',
            name='tipo_cancha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.Tipo_cancha'),
        ),
    ]
