# Generated by Django 2.2.13 on 2020-11-30 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='color',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='color',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
