# Generated by Django 2.2.13 on 2020-10-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunas',
            name='comuna_nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre comuna'),
        ),
        migrations.AlterField(
            model_name='provincias',
            name='provincia_nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre provincia'),
        ),
        migrations.AlterField(
            model_name='regiones',
            name='region_nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre region'),
        ),
    ]
