# Generated by Django 2.2.13 on 2020-10-24 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='provincias',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.Regiones'),
        ),
        migrations.AddField(
            model_name='imagenes',
            name='cancha_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.Cancha'),
        ),
        migrations.AddField(
            model_name='horario',
            name='cancha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.Cancha'),
        ),
        migrations.AddField(
            model_name='horario',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.Color'),
        ),
        migrations.AddField(
            model_name='horario',
            name='dia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.Dias'),
        ),
        migrations.AddField(
            model_name='comunas',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.Provincias'),
        ),
        migrations.AddField(
            model_name='centrodeportivo',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.Comunas'),
        ),
        migrations.AddField(
            model_name='centrodeportivo',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.Provincias'),
        ),
        migrations.AddField(
            model_name='centrodeportivo',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.Regiones'),
        ),
        migrations.AddField(
            model_name='centrodeportivo',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cancha',
            name='centro_dep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.CentroDeportivo'),
        ),
        migrations.AddField(
            model_name='cancha',
            name='servicios',
            field=models.ManyToManyField(to='Base.Servicio'),
        ),
        migrations.AddField(
            model_name='cancha',
            name='superficie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.Superficie'),
        ),
        migrations.AddField(
            model_name='cancha',
            name='tipo_cancha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.Tipo_cancha'),
        ),
        migrations.AddField(
            model_name='cancha',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
