# Generated by Django 2.2.13 on 2020-11-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_auto_20201116_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenes',
            name='titulo',
            field=models.CharField(default=12, max_length=50, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipo_cancha',
            name='imagen',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='deporte_img/', verbose_name='Imagen'),
        ),
    ]
