# Generated by Django 2.2.13 on 2020-10-18 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_auto_20201005_0441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centrodeportivo',
            options={'verbose_name': 'Centro deportivo', 'verbose_name_plural': 'Centros deportivos'},
        ),
    ]
