# Generated by Django 2.2.13 on 2020-10-26 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_auto_20201024_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='imagen',
            field=models.ImageField(max_length=255, null=True, upload_to='cancha_img/', verbose_name='Imagen principal'),
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='cancha_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagen_cancha', to='Base.Cancha'),
        ),
    ]
