# Generated by Django 2.2.13 on 2020-11-29 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_auto_20201129_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenes',
            name='imagen_cancha',
        ),
        migrations.AddField(
            model_name='imagenes',
            name='imagen',
            field=models.ImageField(max_length=255, null=True, upload_to='imagen/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='titulo',
            field=models.CharField(max_length=50, verbose_name='Titulo'),
        ),
    ]
