# Generated by Django 2.2.13 on 2020-10-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_auto_20201026_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='hora_inicio',
            field=models.CharField(max_length=8, null=True, verbose_name='hora inicio'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='hora_termino',
            field=models.CharField(max_length=8, null=True, verbose_name='hora termino'),
        ),
    ]
