# Generated by Django 2.2.13 on 2020-10-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0005_auto_20201026_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='date_end',
            field=models.CharField(max_length=19, verbose_name='date_end'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='date_start',
            field=models.CharField(max_length=19, verbose_name='date_start'),
        ),
    ]
