# Generated by Django 2.2.13 on 2020-11-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0007_auto_20201031_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancha',
            name='descripcion',
            field=models.CharField(max_length=150, verbose_name='Descripcion'),
        ),
    ]
