# Generated by Django 2.2.13 on 2020-11-30 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('direccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True, verbose_name='Nombre de role')),
            ],
        ),
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre de centro deportivo')),
                ('descripcion', models.CharField(max_length=500, null=True, verbose_name='Descripcion del centro')),
                ('imagen_portada', models.ImageField(blank=True, max_length=200, null=True, upload_to='perfil/', verbose_name='Imagen de portada')),
                ('acerca', models.CharField(max_length=1000, null=True, verbose_name='Acerca de nosotros')),
                ('logo', models.ImageField(blank=True, max_length=200, null=True, upload_to='logo/', verbose_name='Logo')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='direccion.Comunas')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='direccion.Provincias')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='direccion.Regiones')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Nombre de usuario')),
                ('nombres', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombres')),
                ('apellidos', models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellidos')),
                ('direccion', models.CharField(max_length=100, null=True, verbose_name='Direccion')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('imagen', models.ImageField(max_length=200, null=True, upload_to='perfil/', verbose_name='Imagen de Perfil')),
                ('usuario_activo', models.BooleanField(default=True)),
                ('usuario_administrador', models.BooleanField(default=False)),
                ('centro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Centro')),
                ('comuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='direccion.Comunas')),
                ('provincia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='direccion.Provincias')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='direccion.Regiones')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Role')),
            ],
            options={
                'permissions': [('permiso_desde_codigo', 'Este es un permiso creado desde código'), ('segundo_permiso_codigo', 'Segundo permiso creado desde codigo')],
            },
        ),
    ]
