# Generated by Django 2.2.13 on 2020-12-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centro',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electronico'),
        ),
        migrations.AddField(
            model_name='centro',
            name='facebook',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='centro',
            name='fono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numero de contacto'),
        ),
        migrations.AddField(
            model_name='centro',
            name='instagram',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='centro',
            name='twitter',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Twitter'),
        ),
    ]
