# Generated by Django 2.2.13 on 2020-11-29 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centro',
            name='acerca',
            field=models.CharField(max_length=1000, null=True, verbose_name='Acerca de nosotros'),
        ),
    ]
